#page title
page_title                                : OffCampus                                 

# App Info
ios_app_id                                : 

appstore_link                             : https://testflight.apple.com/join/KBUVCgQM
playstore_link                            : https://appdistribution.firebase.dev/i/8f3f2106278c0e9e
presskit_download_link                    : 

app_icon                                  : /assets/appicon.png
app_name                                  : OffCampus
app_price                                 : 
app_description                           : OffCampus is an essential app for university life, meeting new friends and discussing about courses and interests.

enable_smart_app_banner                   : true



# Information About Yourself
your_name                                 : Joshua Tang
your_link                                 : https://zeshuaro.github.io/portfolio/
your_city                                 : 
email_address                             : zeshuaro@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : zeshuaro
linkedin_username                         : joshua-tang
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : University Friends
    description                           : Meet new friends from your degree, or across different universities and faculties.
    fontawesome_icon_name                 : user-friends

  - title                                 : Match Users
    description                           : Find users who are most/least similar to your field of study, or simply some random ones.
    fontawesome_icon_name                 : search

  - title                                 : Search & Filter Users
    description                           : Looking for someone? Search users by keywords or filter by university and faculty.
    fontawesome_icon_name                 : filter
    
  - title                                 : Discuss Coursework
    description                           : Find and join group chats for your courses to discuss about lectures and assignments.
    fontawesome_icon_name                 : university

  - title                                 : Pre-Loaded Course Chats
    description                           : No more 'Is there a group chat for COMPXXXX?' on CSESoc Facebook group.
    fontawesome_icon_name                 : smile-wink

  - title                                 : Messaging
    description                           : Private chats for you and your friends and course chats for your course cohort.
    fontawesome_icon_name                 : comment



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : /assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown